alter table public.vacunas_desparasitaciones
add column if not exists valor numeric;

comment on column public.vacunas_desparasitaciones.valor is 'Valor cobrado por vacuna o desparasitacion.';

create table if not exists public.examenes (
  id bigint generated by default as identity primary key,
  paciente_id bigint not null references public.pacientes(id),
  tipo_examen text not null,
  valor numeric,
  fecha_toma_muestra date not null,
  tipo_muestra text,
  observaciones text,
  fecha_creacion timestamp with time zone default now()
);

comment on table public.examenes is 'Tabla con examenes solicitados o tomados a pacientes.';
comment on column public.examenes.paciente_id is 'Paciente asociado al examen.';
comment on column public.examenes.tipo_examen is 'Tipo de examen registrado.';
comment on column public.examenes.valor is 'Valor cobrado por el examen.';
comment on column public.examenes.fecha_toma_muestra is 'Fecha de toma de muestra del examen.';
comment on column public.examenes.tipo_muestra is 'Tipo de muestra tomada para el examen.';

alter table public.examenes enable row level security;

grant select, insert, update on table public.examenes to authenticated;
grant usage, select on sequence public.examenes_id_seq to authenticated;

drop policy if exists "authenticated_read_examenes" on public.examenes;
drop policy if exists "authenticated_insert_examenes" on public.examenes;
drop policy if exists "authenticated_update_examenes" on public.examenes;

create policy "authenticated_read_examenes"
on public.examenes
for select
to authenticated
using (true);

create policy "authenticated_insert_examenes"
on public.examenes
for insert
to authenticated
with check (true);

create policy "authenticated_update_examenes"
on public.examenes
for update
to authenticated
using (true)
with check (true);
