-- Referencia del esquema real usado por la app SEMEVET.
-- Las tablas ya existen en Supabase con estos nombres exactos.

create table if not exists "Tutores" (
  id bigint generated by default as identity primary key,
  "Nombre" text not null,
  "Telefono" text not null,
  "Correo" text,
  "Direccion" text not null,
  "Comuna" text,
  "Observaciones" text
);

create table if not exists "Usuarios" (
  id uuid primary key references auth.users(id) on delete cascade,
  nombre text not null,
  email text not null unique,
  rol text not null default 'veterinario',
  telefono text,
  activo boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists "Pacientes" (
  id bigint generated by default as identity primary key,
  id_tutor bigint,
  "Nombre" text not null,
  "Especie" text not null,
  "Raza" text,
  "Sexo" text,
  "Edad" numeric,
  "Peso" numeric,
  "Enfermedades_previas" text,
  "Esterilizado" boolean,
  "Numero_partos" integer,
  "Microchip" text,
  "Alergias" text,
  "Cirugias_previas" text,
  "Vive_con_animales" boolean,
  "Cuales" text
);

create table if not exists "Consultas" (
  id bigint generated by default as identity primary key,
  "Paciente_id" bigint not null,
  "Fecha" date not null,
  "Tipo atención" text,
  "Motivo" text not null,
  "Anamnesis" text,
  "Examen_fisico" text,
  "Temperatura" numeric,
  "Frecuencia_cardiaca" integer,
  "Frecuencia_respiratoria" integer,
  "Mucosas" text,
  "TLLC" text,
  "Diagnostico_presuntivo" text,
  "Diagnostico_definitivo" text,
  "Tratamiento" text,
  "indicaciones" text,
  "Proximo control" date,
  "Valor" numeric,
  "Estado_pago" text
);

create table if not exists "Vacunas_Desparacitaciones" (
  id bigint generated by default as identity primary key,
  "Paciente_id" bigint not null,
  "Tipo" text not null,
  "Producto" text not null,
  "Fecha_aplicacion" date not null,
  "Proxima_fecha" date,
  "Observaciones" text
);
